### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DominiqueCaron** [DominiqueCaron/Ouranos-WorkersHealth#1]
## Week June 4th
- [ ] Test functions
- [ ] Optimize speed getmodelvp() et setClimgrids()
- [ ] Add comments
- [ ] Test how much time for one polygon/scenario
- [ ] Parallel some functions
